
# ----------------------------
# 1️⃣ Build stage
# ----------------------------
FROM node:alpine AS builder

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm ci

# Copy source
COPY . .

# # Remove dev dependencies
RUN npm prune --production


# ----------------------------
# 2️⃣ Production stage (Distroless)
# ----------------------------
FROM gcr.io/distroless/nodejs20-debian12

WORKDIR /app

# Copy only required files
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

# Expose port
EXPOSE 3000

# Start app (NO npm, NO shell)
# CMD ["dist/dist/main.js"]
CMD [ "node","src/index.js" ]








