
# ----------------------------
# 1️⃣ Build stage
# ----------------------------
FROM node:alpine AS builder

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm ci

# Copy source
COPY . .

RUN npm run build

# # Remove dev dependencies
RUN npm prune --production


# ----------------------------
# 2️⃣ Production stage (Distroless)
# ----------------------------
FROM gcr.io/distroless/nodejs20-debian12

WORKDIR /app

# Copy only needed files
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

# Expose port
EXPOSE 3001


# Start app (NO npm, NO shell)
CMD ["npm", "start"]








